name: 'Token-Bureau'
description: 'Generate GitHub App tokens with OIDC verification'
inputs:
  token-bureau-url:
    description: 'URL of the Token-Bureau service'
    required: true
  audience:
    description: 'OIDC audience value'
    required: true
  permissions:
    description: |
      JSON string of GitHub App permissions to request. Must be allowed by server configuration.
      Example: '{"contents": "read", "issues": "write"}'
      Available permissions: contents, metadata, issues, pull_requests, deployments, packages,
      actions, security_events, statuses, checks, discussions, pages, workflows
      Access levels: read, write
    required: false

outputs:
  token:
    description: 'The generated GitHub App token'
  expires_at:
    description: 'Token expiration timestamp'
  installation_id:
    description: 'GitHub App installation ID'

runs:
  using: 'node20'
  main: 'dist/index.cjs'

branding:
  icon: 'lock'
  color: 'blue'
